<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="OneOf" />
    <PackageReference Include="Marten" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\CartItem\Entities\" />
    <Folder Include="Links\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Common\IEndpointHandler.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="..\..\..\Common\Contracts\SharedClasses\OptionsPattern\PostgreSQL\PostgreSQLConfig.json" 
             Link="Links\PostgreSQLConfig.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
