name: DotNetAdv

services:
  # ===========================================================================
  # Service 1: PostgreSQL Database
  # ===========================================================================
  postgres:
    # The Docker image to download. '15-alpine' is a lightweight version of Postgres 15.
    image: postgres:18.1-alpine3.23
    
    # Custom name for the container so you can easily find it (e.g., 'docker stop infra_postgres')
    container_name: Database
    
    # Ensures the container starts up automatically if it crashes or if Docker restarts.
    restart: always
    
    # Environment variables to configure the database credentials on initialization.
    environment:
      POSTGRES_USER: admin           # The superuser name
      POSTGRES_PASSWORD: password123 # The superuser password
      POSTGRES_DB: Catalog           # A default database created on startup
      
    # Port Mapping: "HOST_PORT:CONTAINER_PORT"
    # We map host port 10105 to the standard Postgres port 5432.
    ports:
      - "10105:5432"
      
    # Volume Mapping: "VOLUME_NAME:INTERNAL_PATH"
    # Maps a named volume to the internal folder where Postgres stores data.
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
    # Connects this container to our custom network.
    networks:
      - internal_network
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ===========================================================================
  # Service 2: RabbitMQ Message Broker
  # ===========================================================================
  rabbitmq:
    # Uses the 'management' tag which includes the web UI plugin pre-installed.
    image: rabbitmq:4.2.2-management-alpine
    
    container_name: MessageQueue
    restart: always
    
    # Default credentials for RabbitMQ.
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
    ports:
      # Port 5672 is for AMQP (App-to-App communication).
      # Mapped to Host Port 10106.
      - "10106:5672"
      
      # Port 15672 is for the Management Web Dashboard.
      # Mapped to Host Port 10107.
      - "10107:15672"
    
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    
    # Persist RabbitMQ queue data and messages.
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
    networks:
      - internal_network

  # ===========================================================================
  # Service 3: Keycloak Identity Management
  # ===========================================================================
  keycloack:
    image: keycloak/keycloak:26.5
    container_name: IdentityServer
    restart: always
    command: start-dev
    environment:
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_DB_USERNAME: keycloakuser
        KC_DB_PASSWORD: keycloak123
        KC_DB_SCHEMA: keycloak
        KC_HOSTNAME: localhost
        KC_HTTP_ENABLED: "true"
        KC_HEALTH_ENABLED: true
    ports:
      - "10108:8080"
    networks:
      - internal_network
    volumes:
      - keycloak_data:/opt/keycloak/data
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3; grep 'HTTP/1.1 200 OK' <&3"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      postgres:
        condition:  service_healthy

# ===========================================================================
# Volumes Section
# Defines persistent storage that survives container deletion.
# ===========================================================================
volumes:
  postgres_data:
    driver: local  # Uses the standard local Docker driver
  rabbitmq_data:
    driver: local
  keycloak_data:
    driver: local

# ===========================================================================
# Networks Section
# Defines a private network for these services to communicate.
# ===========================================================================
networks:
  internal_network:
    driver: bridge # Standard network type for containers on the same host