CREATE TABLE [Category] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL,
    [ImageUrl] NVARCHAR(MAX) NULL,
    [ParentCategoryId] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [Product] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [ImageUrl] NVARCHAR(MAX) NULL,
    [Price] DECIMAL(18, 2) NOT NULL,
    [Ammount] INT NOT NULL,
    [CategoryId] UNIQUEIDENTIFIER NOT NULL
);